const list_osm_errors =
[
    {
        "country_code_iso2": "KR",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [2] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/312297590",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "UA",
        "name": "CablesNumber",
        "description": "Incorrect cables number [3] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/502846474",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "LV",
        "name": "ConnectionInBetweenEnds",
        "description": "Connection of a power line to (1) through the node (2)",
        "osmid1": "node/way/1229158679",
        "osmid2": "node/11398889468",
        "osmid": null,
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "NL",
        "name": "CABLESDifferenceOnJunction",
        "description": "cables difference on line node https://www.openstreetmap.org/node/13119494947 | cables = [3, 1], (first value kept)",
        "osmid1": null,
        "osmid2": null,
        "osmid": "node/13119494947",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "UA",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [2] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/313426144",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "MM",
        "name": "SameOriginDestination",
        "description": "Same origin-destination on graph build:['node/11364408195', 'node/11364408195'] | edges = [('node/11364408187', 'node/11364408195'), ('node/11364408187', 'node/11364408195')] | str = way/1225458735*0;way/1225458735*0",
        "osmid1": null,
        "osmid2": null,
        "osmid": null,
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "PT",
        "name": "CablesNumber",
        "description": "Incorrect cables number [6] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1232033620",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "DE",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/485465528",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "TW",
        "name": "CablesNumber",
        "description": "Incorrect cables number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/516532539",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "MD",
        "name": "CablesNumber",
        "description": "Incorrect cables number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1017757407*2",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "VE",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [2] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/701721731",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "DE",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [1] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/818010492",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "AR",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/261599785",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "IN",
        "name": "CablesNumber",
        "description": "Incorrect cables number [6] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/409304513",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "AU",
        "name": "CablesNumber",
        "description": "Incorrect cables number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1317477931",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "CA",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/432141426*1",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "PT",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [1] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/340102184",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "ME",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1308883439",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "ZA",
        "name": "IncorrectTopology",
        "description": "Topology Problem on node(s) - 2 nodes expected :['way/84200602'] / You might need to split the way",
        "osmid1": null,
        "osmid2": null,
        "osmid": null,
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "IL",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [2] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/469451199",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "CO",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [2] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/444500538",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "FI",
        "name": "CablesNumber",
        "description": "Incorrect cables number [3] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/43857610*2",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "TW",
        "name": "CablesNumber",
        "description": "Incorrect cables number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/666653300*0",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "GT",
        "name": "ConnectionInBetweenEnds",
        "description": "Connection of a power line to (1) through the node (2)",
        "osmid1": "node/way/1248255040",
        "osmid2": "node/11603194194",
        "osmid": null,
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "VN",
        "name": "ConnectionInBetweenEnds",
        "description": "Connection of a power line to (1) through the node (2)",
        "osmid1": "node/way/1176867376",
        "osmid2": "node/10933617988",
        "osmid": null,
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "CL",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1255825258",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "LV",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1058393370",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "IR",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [1] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1308646316",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "KP",
        "name": "CablesNumber",
        "description": "Incorrect cables number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1236980810",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "CA",
        "name": "CablesNumber",
        "description": "Incorrect cables number [3;3] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/906699576",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "LV",
        "name": "CablesNumber",
        "description": "Incorrect cables number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/734430373*2",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "TR",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/995318803",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "BR",
        "name": "CablesNumber",
        "description": "Incorrect cables number [3] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/101815970",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "NL",
        "name": "CablesNumber",
        "description": "Incorrect cables number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1427132318",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "MM",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1225536602",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "IN",
        "name": "CablesNumber",
        "description": "Incorrect cables number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/168519055",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "NL",
        "name": "CABLESDifferenceOnJunction",
        "description": "cables difference on line node https://www.openstreetmap.org/node/13120305672 | cables = [3, 1], (first value kept)",
        "osmid1": null,
        "osmid2": null,
        "osmid": "node/13120305672",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "BR",
        "name": "CABLESDifferenceOnJunction",
        "description": "cables difference on line node https://www.openstreetmap.org/node/5223448028 | cables = [3, 1], (first value kept)",
        "osmid1": null,
        "osmid2": null,
        "osmid": "node/5223448028",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "TJ",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [1] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1382413123",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "DE",
        "name": "CablesNumber",
        "description": "Incorrect cables number [3] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1198038317",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "PK",
        "name": "CablesNumber",
        "description": "Incorrect cables number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1311209269",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "CA",
        "name": "SameOriginDestination",
        "description": "Same origin-destination on graph build:['way/232194254', 'way/232194254'] | edges = [('node/2703734475', 'way/232194254'), ('node/2703734475', 'way/232194254')] | str = way/316502418;way/316502418",
        "osmid1": null,
        "osmid2": null,
        "osmid": null,
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "CA",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/504758446",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "NZ",
        "name": "CablesNumber",
        "description": "Incorrect cables number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1278651517",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "TR",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/815700061",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "VN",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/549812388",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "SE",
        "name": "SameOriginDestination",
        "description": "Same origin-destination on graph build:['node/3252878475', 'node/3252878475'] | edges = [('node/9436471164', 'node/3252878475'), ('node/9436471164', 'node/3252878475')] | str = way/318891960*0;way/318891960*0",
        "osmid1": null,
        "osmid2": null,
        "osmid": null,
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "CU",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/146977096",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "AU",
        "name": "CablesNumber",
        "description": "Incorrect cables number [1] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/680650762",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "AU",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/214309966*0",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "LY",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/249645005*1",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "IN",
        "name": "ConnectionInBetweenEnds",
        "description": "Connection of a power line to (1) through the node (2)",
        "osmid1": "node/way/1370430867",
        "osmid2": "node/12692200736",
        "osmid": null,
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "UA",
        "name": "CablesNumber",
        "description": "Incorrect cables number [3] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/265961347*1",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "BR",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [1] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/288400261",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "ZA",
        "name": "CablesNumber",
        "description": "Incorrect cables number [3] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/223064703",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "ID",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1313929281",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "IR",
        "name": "CablesNumber",
        "description": "Incorrect cables number [6] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/837125662",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "SK",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [1] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1137360183",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "NL",
        "name": "CABLESDifferenceOnJunction",
        "description": "cables difference on line node https://www.openstreetmap.org/node/13120303039 | cables = [3, 1], (first value kept)",
        "osmid1": null,
        "osmid2": null,
        "osmid": "node/13120303039",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "DE",
        "name": "MemberRoleInCircuit",
        "description": "Problem of role 'abandoned' of (1) in circuit relation (2)",
        "osmid1": "way/88179265",
        "osmid2": "relation/1311806",
        "osmid": null,
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "IN",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [1] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1251833498*2",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "MN",
        "name": "ConnectionInBetweenEnds",
        "description": "Connection of a power line to (1) through the node (2)",
        "osmid1": "node/way/866643810",
        "osmid2": "node/8077918408",
        "osmid": null,
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "MD",
        "name": "ConnectionInBetweenEnds",
        "description": "Connection of a power line to (1) through the node (2)",
        "osmid1": "node/way/1017425991",
        "osmid2": "node/9384424749",
        "osmid": null,
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "DE",
        "name": "ConnectionInBetweenEnds",
        "description": "Connection of a power line to (1) through the node (2)",
        "osmid1": "node/way/785199147",
        "osmid2": "node/2809580808",
        "osmid": null,
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "VN",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1374565938",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "IN",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1356747016*6",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "IN",
        "name": "ConnectionInBetweenEnds",
        "description": "Connection of a power line to (1) through the node (2)",
        "osmid1": "node/way/341599744",
        "osmid2": "node/3487450520",
        "osmid": null,
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "CU",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/146977089",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "DE",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1102804719",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "EE",
        "name": "VOLTAGEDifferenceOnJunction",
        "description": "voltage difference on line node https://www.openstreetmap.org/node/410397803 | voltage = ['330000;110000', '330000'], (first value kept)",
        "osmid1": null,
        "osmid2": null,
        "osmid": "node/410397803",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "TR",
        "name": "CABLESDifferenceOnJunction",
        "description": "cables difference on line node https://www.openstreetmap.org/node/1414537188 | cables = [None, '2'], (first value kept)",
        "osmid1": null,
        "osmid2": null,
        "osmid": "node/1414537188",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "AU",
        "name": "CablesNumber",
        "description": "Incorrect cables number [3] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/170195252",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "MD",
        "name": "CablesNumber",
        "description": "Incorrect cables number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1008636844",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "IN",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/418896798",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "DE",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [2] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/269548887",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "TW",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [2] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/202162589*0",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "CA",
        "name": "CablesNumber",
        "description": "Incorrect cables number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1212144072",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "BR",
        "name": "CablesNumber",
        "description": "Incorrect cables number [3] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/599337237",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "SA",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [1] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1326263756",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "UA",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [2] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/372260309",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "IN",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/393009667",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "BY",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [1] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/300347049",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "BR",
        "name": "CablesNumber",
        "description": "Incorrect cables number [3] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/554937623",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "BY",
        "name": "CablesNumber",
        "description": "Incorrect cables number [3] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/235391289",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "IN",
        "name": "CablesNumber",
        "description": "Incorrect cables number [6] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1097586863",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "ZA",
        "name": "ConnectionInBetweenEnds",
        "description": "Connection of a power line to (1) through the node (2)",
        "osmid1": "node/way/456947799",
        "osmid2": "node/4538202512",
        "osmid": null,
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "NG",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/671376838*0",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "CA",
        "name": "CablesNumber",
        "description": "Incorrect cables number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/73157138",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "CA",
        "name": "CablesNumber",
        "description": "Incorrect cables number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/639137296",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "IL",
        "name": "CablesNumber",
        "description": "Incorrect cables number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1174704013",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "IL",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [1] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/682206577",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "PT",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [1] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1230373509",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "SE",
        "name": "ConnectionInBetweenEnds",
        "description": "Connection of a power line to (1) through the node (2)",
        "osmid1": "node/way/1014950964",
        "osmid2": "node/9362853609",
        "osmid": null,
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "HR",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/773740230",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "AU",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [1] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/657110858",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "NO",
        "name": "CablesNumber",
        "description": "Incorrect cables number [3] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/617511817",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "VN",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/430731461",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "EC",
        "name": "CablesNumber",
        "description": "Incorrect cables number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1281261574",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "AT",
        "name": "CablesNumber",
        "description": "Incorrect cables number [None] of type <class 'NoneType'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/713387391",
        "id": null,
        "objecttype": null,
        "details": null
    },
    {
        "country_code_iso2": "MX",
        "name": "CircuitsNumber",
        "description": "Incorrect circuit number [1] of type <class 'str'>",
        "osmid1": null,
        "osmid2": null,
        "osmid": "way/1340430067",
        "id": null,
        "objecttype": null,
        "details": null
    }
];
